name: Deploy

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    

  deploy:
    steps:
      - name: Start App
      env:
        BOT_TOKEN: ${{ secrets.SECRET_FRONEND_BOT_TOKEN }}
        MEME_API: ${{ secrets.SECRET_MEME_API }}
      run: pm2 delete -s shen_bot || :; pm2 start npm --name "shen_bot" -- start; pm2 save